services:

  event-gateway-service:
    image: eclipse-temurin:20-jre-alpine
    container_name: gateway-service
    ports:
      - "8084:8090"
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar event-gateway-service-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MYAPP_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - promo-network

networks:
  promo-network:
    name: promo-infrastructure_default
    external: true

