services:

  event-gateway-service:
    build: .
    container_name: gateway-service
    ports:
      - "8084:8090"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MYAPP_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - promo-network

networks:
  promo-network:
    name: promo-shared-network
    external: true

