server:
  port: 8090

spring:
  application:
    name: event-gateway-service
  docker:
    compose:
      enabled: false




  kafka:
    bootstrap-servers: kafka:9096


    consumer:
      group-id: gateway-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    gateway:
      routes:
        - id: websocket_streaming_route
          uri: ws://localhost:8090
          predicates:
            - Path=/ws/events/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

myapp:
  kafka:
    bootstrap-servers: ${MYAPP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      game-events: ${KAFKA_TOPIC_GAME:game.events}
      tournament-events: ${KAFKA_TOPIC_TOURNAMENT:tournament.events}
      leaderboard-events: ${KAFKA_TOPIC_LEADERBOARD:leaderboard.events}



