server:
  port: 8090

spring:
  application:
    name: event-gateway-service
  docker:
    compose:
      enabled: false




  kafka:
    bootstrap-servers: kafka:9096


    consumer:
      group-id: gateway-service
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.company.*"

        spring.json.use.type.mapper.for.collections: false

        spring.json.type.mapping: >-
          leaderboard_event:com.company.event_gateway_service.event.LeaderboardEvent,
          com.company.promo.service.leaderboard.LeaderboardEvent:com.company.event_gateway_service.event.LeaderboardEvent,
          game_event:com.company.event_gateway_service.event.GameEvent,
          com.company.promobridge.GameEvent:com.company.event_gateway_service.event.GameEvent,
          tournament_event:com.company.event_gateway_service.event.TournamentEvent,
          com.company.promobridge.TournamentEvent:com.company.event_gateway_service.event.TournamentEvent
      spring.kafka.jackson.serialization.inclusion: non_null

  cloud:
    gateway:
      routes:
        - id: websocket_streaming_route
          uri: ws://localhost:8090
          predicates:
            - Path=/ws/events/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

myapp:
  kafka:
    bootstrap-servers: ${MYAPP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      game-events: ${KAFKA_TOPIC_GAME:game.events}
      tournament-events: ${KAFKA_TOPIC_TOURNAMENT:tournament.events}
      leaderboard-events: ${KAFKA_TOPIC_LEADERBOARD:leaderboard.events}



